// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'cd4a4d519c29972c91c5c3e86f9c1a51758de97e134b99801cb922d77d811eb9'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly PineScript: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly content: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly type: 'INDICATOR' | 'STRATEGY';
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly TradeRecord: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly accountId: CodecTypes['pg/int4@1']['output'];
      readonly underlyingName: CodecTypes['pg/text@1']['output'];
      readonly underlyingCode: CodecTypes['pg/text@1']['output'];
      readonly direction: 'LONG' | 'SHORT';
      readonly quantity: CodecTypes['pg/numeric@1']['output'];
      readonly openTime: CodecTypes['pg/timestamptz@1']['output'];
      readonly openPrice: CodecTypes['pg/numeric@1']['output'];
      readonly openReason: CodecTypes['pg/text@1']['output'] | null;
      readonly screenshot: CodecTypes['pg/text@1']['output'] | null;
      readonly closeTime: CodecTypes['pg/timestamptz@1']['output'] | null;
      readonly closePrice: CodecTypes['pg/numeric@1']['output'] | null;
      readonly closeReason: CodecTypes['pg/text@1']['output'] | null;
      readonly realizedPnl: CodecTypes['pg/numeric@1']['output'] | null;
      readonly fee: CodecTypes['pg/numeric@1']['output'];
      readonly extraJson: CodecTypes['pg/json@1']['output'] | null;
    };
    readonly TradingAccount: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly account: CodecTypes['pg/text@1']['output'];
      readonly currency: CodecTypes['pg/text@1']['output'];
    };
    readonly Watchlist: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly sortOrder: CodecTypes['pg/int4@1']['output'];
    };
    readonly WatchlistItem: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly watchlistId: CodecTypes['pg/int4@1']['output'];
      readonly instrumentId: CodecTypes['pg/int4@1']['output'];
      readonly sortOrder: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly PineScript: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly content: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly type: 'INDICATOR' | 'STRATEGY';
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly TradeRecord: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly accountId: CodecTypes['pg/int4@1']['input'];
      readonly underlyingName: CodecTypes['pg/text@1']['input'];
      readonly underlyingCode: CodecTypes['pg/text@1']['input'];
      readonly direction: 'LONG' | 'SHORT';
      readonly quantity: CodecTypes['pg/numeric@1']['input'];
      readonly openTime: CodecTypes['pg/timestamptz@1']['input'];
      readonly openPrice: CodecTypes['pg/numeric@1']['input'];
      readonly openReason: CodecTypes['pg/text@1']['input'] | null;
      readonly screenshot: CodecTypes['pg/text@1']['input'] | null;
      readonly closeTime: CodecTypes['pg/timestamptz@1']['input'] | null;
      readonly closePrice: CodecTypes['pg/numeric@1']['input'] | null;
      readonly closeReason: CodecTypes['pg/text@1']['input'] | null;
      readonly realizedPnl: CodecTypes['pg/numeric@1']['input'] | null;
      readonly fee: CodecTypes['pg/numeric@1']['input'];
      readonly extraJson: CodecTypes['pg/json@1']['input'] | null;
    };
    readonly TradingAccount: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly account: CodecTypes['pg/text@1']['input'];
      readonly currency: CodecTypes['pg/text@1']['input'];
    };
    readonly Watchlist: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly sortOrder: CodecTypes['pg/int4@1']['input'];
    };
    readonly WatchlistItem: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly watchlistId: CodecTypes['pg/int4@1']['input'];
      readonly instrumentId: CodecTypes['pg/int4@1']['input'];
      readonly sortOrder: CodecTypes['pg/int4@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly pineScript: {
      readonly content: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly type: 'INDICATOR' | 'STRATEGY';
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly tradeRecord: {
      readonly accountId: CodecTypes['pg/int4@1']['output'];
      readonly closePrice: CodecTypes['pg/numeric@1']['output'] | null;
      readonly closeReason: CodecTypes['pg/text@1']['output'] | null;
      readonly closeTime: CodecTypes['pg/timestamptz@1']['output'] | null;
      readonly direction: 'LONG' | 'SHORT';
      readonly extraJson: CodecTypes['pg/json@1']['output'] | null;
      readonly fee: CodecTypes['pg/numeric@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly openPrice: CodecTypes['pg/numeric@1']['output'];
      readonly openReason: CodecTypes['pg/text@1']['output'] | null;
      readonly openTime: CodecTypes['pg/timestamptz@1']['output'];
      readonly quantity: CodecTypes['pg/numeric@1']['output'];
      readonly realizedPnl: CodecTypes['pg/numeric@1']['output'] | null;
      readonly screenshot: CodecTypes['pg/text@1']['output'] | null;
      readonly underlyingCode: CodecTypes['pg/text@1']['output'];
      readonly underlyingName: CodecTypes['pg/text@1']['output'];
    };
    readonly tradingAccount: {
      readonly account: CodecTypes['pg/text@1']['output'];
      readonly currency: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly watchlist: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly sortOrder: CodecTypes['pg/int4@1']['output'];
    };
    readonly watchlistItem: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly instrumentId: CodecTypes['pg/int4@1']['output'];
      readonly sortOrder: CodecTypes['pg/int4@1']['output'];
      readonly watchlistId: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly pineScript: {
      readonly content: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly type: 'INDICATOR' | 'STRATEGY';
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly tradeRecord: {
      readonly accountId: CodecTypes['pg/int4@1']['input'];
      readonly closePrice: CodecTypes['pg/numeric@1']['input'] | null;
      readonly closeReason: CodecTypes['pg/text@1']['input'] | null;
      readonly closeTime: CodecTypes['pg/timestamptz@1']['input'] | null;
      readonly direction: 'LONG' | 'SHORT';
      readonly extraJson: CodecTypes['pg/json@1']['input'] | null;
      readonly fee: CodecTypes['pg/numeric@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly openPrice: CodecTypes['pg/numeric@1']['input'];
      readonly openReason: CodecTypes['pg/text@1']['input'] | null;
      readonly openTime: CodecTypes['pg/timestamptz@1']['input'];
      readonly quantity: CodecTypes['pg/numeric@1']['input'];
      readonly realizedPnl: CodecTypes['pg/numeric@1']['input'] | null;
      readonly screenshot: CodecTypes['pg/text@1']['input'] | null;
      readonly underlyingCode: CodecTypes['pg/text@1']['input'];
      readonly underlyingName: CodecTypes['pg/text@1']['input'];
    };
    readonly tradingAccount: {
      readonly account: CodecTypes['pg/text@1']['input'];
      readonly currency: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly watchlist: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly sortOrder: CodecTypes['pg/int4@1']['input'];
    };
    readonly watchlistItem: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly instrumentId: CodecTypes['pg/int4@1']['input'];
      readonly sortOrder: CodecTypes['pg/int4@1']['input'];
      readonly watchlistId: CodecTypes['pg/int4@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly pineScript: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly content: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'pineScript_type_idx_b6b604ea';
                  readonly prefix: 'pineScript_type_idx';
                  readonly columns: readonly ['type'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly tradeRecord: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly accountId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly underlyingName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly underlyingCode: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly direction: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly quantity: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly openTime: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                };
                readonly openPrice: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly openReason: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly screenshot: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly closeTime: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: true;
                };
                readonly closePrice: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly closeReason: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly realizedPnl: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly fee: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly extraJson: {
                  readonly nativeType: 'json';
                  readonly codecId: 'pg/json@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'tradeRecord_accountId_idx_cbfb3085';
                  readonly prefix: 'tradeRecord_accountId_idx';
                  readonly columns: readonly ['accountId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'tradeRecord_openTime_idx_459da85f';
                  readonly prefix: 'tradeRecord_openTime_idx';
                  readonly columns: readonly ['openTime'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tradeRecord';
                    readonly columns: readonly ['accountId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tradingAccount';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly tradingAccount: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly account: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly currency: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['account'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly watchlist: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly sortOrder: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'watchlist_sortOrder_idx_ebf2eac2';
                  readonly prefix: 'watchlist_sortOrder_idx';
                  readonly columns: readonly ['sortOrder'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly watchlistItem: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly watchlistId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly instrumentId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly sortOrder: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['watchlistId', 'instrumentId'] }];
              indexes: readonly [
                {
                  readonly name: 'watchlistItem_watchlistId_sortOrder_idx_04bb0458';
                  readonly prefix: 'watchlistItem_watchlistId_sortOrder_idx';
                  readonly columns: readonly ['watchlistId', 'sortOrder'];
                  readonly unique: false;
                },
                {
                  readonly name: 'watchlistItem_watchlistId_idx_bfe7654a';
                  readonly prefix: 'watchlistItem_watchlistId_idx';
                  readonly columns: readonly ['watchlistId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'watchlistItem';
                    readonly columns: readonly ['watchlistId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'watchlist';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly PineScriptType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['INDICATOR', 'STRATEGY'];
            };
            readonly TradeDirection: {
              readonly kind: 'valueSet';
              readonly values: readonly ['LONG', 'SHORT'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly tradingAccount: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'TradingAccount';
    };
    readonly tradeRecord: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'TradeRecord';
    };
    readonly watchlist: { readonly namespace: 'public' & NamespaceId; readonly model: 'Watchlist' };
    readonly watchlistItem: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'WatchlistItem';
    };
    readonly pineScript: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'PineScript';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly PineScript: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly content: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'pineScript';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly content: { readonly column: 'content' };
                readonly description: { readonly column: 'description' };
                readonly type: { readonly column: 'type' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly TradeRecord: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly accountId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly underlyingName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly underlyingCode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly direction: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly openTime: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly openPrice: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly openReason: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly screenshot: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly closeTime: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly closePrice: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly closeReason: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly realizedPnl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly fee: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly extraJson: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/json@1' };
              };
            };
            readonly relations: {
              readonly account: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'TradingAccount';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['accountId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'tradeRecord';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly accountId: { readonly column: 'accountId' };
                readonly underlyingName: { readonly column: 'underlyingName' };
                readonly underlyingCode: { readonly column: 'underlyingCode' };
                readonly direction: { readonly column: 'direction' };
                readonly quantity: { readonly column: 'quantity' };
                readonly openTime: { readonly column: 'openTime' };
                readonly openPrice: { readonly column: 'openPrice' };
                readonly openReason: { readonly column: 'openReason' };
                readonly screenshot: { readonly column: 'screenshot' };
                readonly closeTime: { readonly column: 'closeTime' };
                readonly closePrice: { readonly column: 'closePrice' };
                readonly closeReason: { readonly column: 'closeReason' };
                readonly realizedPnl: { readonly column: 'realizedPnl' };
                readonly fee: { readonly column: 'fee' };
                readonly extraJson: { readonly column: 'extraJson' };
              };
            };
          };
          readonly TradingAccount: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly account: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly currency: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly tradeRecords: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'TradeRecord';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['accountId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'tradingAccount';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly account: { readonly column: 'account' };
                readonly currency: { readonly column: 'currency' };
              };
            };
          };
          readonly Watchlist: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sortOrder: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly items: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'WatchlistItem';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['watchlistId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'watchlist';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly sortOrder: { readonly column: 'sortOrder' };
              };
            };
          };
          readonly WatchlistItem: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly watchlistId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly instrumentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly sortOrder: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly watchlist: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Watchlist';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['watchlistId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'watchlistItem';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly watchlistId: { readonly column: 'watchlistId' };
                readonly instrumentId: { readonly column: 'instrumentId' };
                readonly sortOrder: { readonly column: 'sortOrder' };
              };
            };
          };
        };
        readonly enum: {
          readonly TradeDirection: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'LONG'; readonly value: 'LONG' },
              { readonly name: 'SHORT'; readonly value: 'SHORT' },
            ];
          };
          readonly PineScriptType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'INDICATOR'; readonly value: 'INDICATOR' },
              { readonly name: 'STRATEGY'; readonly value: 'STRATEGY' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
